Repository SUNET/eduid-front, pull requests merged in 2020-08, with the labels that each got.

#388 INPUT: styling new customInput in personal data
  i18n/src/login/translation/messageIndex.json
  src/components/PersonalData.js
  src/login/components/Inputs/CustomInput.js
  src/login/styles/_anti-bootstrap.scss
  src/login/styles/_inputs.scss
  src/login/styles/_label.scss
  src/login/translation/defaultMessages/errors.js
  src/login/translation/languages/en.json
  src/login/translation/messageIndex.js
  src/login/translation/src/i18n-messages.json
  src/login/translation/src/login/translation/defaultMessages/errors.json
  src/login/translation/src/login/translation/messageIndex.json
Labels: investigate, styling

#390 BUTTON: Misalign button in firefox
  src/login/styles/_Emails.scss
  src/login/styles/_SignupMain.scss
  src/login/styles/_buttons.scss
Labels: bug, styling

#395 CONFIRM IDENTITY: Uncaught ReferenceError on Identity tab
  src/components/VerifyIdentity.js
Labels: bug

#397 REGISTRATION: Fix Swe copy issue when process complete
  src/login/translation/languages/sv.json
Labels: bug, copy

#401 Change nin_display.profile.main_title text lowcase to capitalise
  i18n/src/login/translation/defaultMessages/userProfile.json
  src/login/translation/defaultMessages/userProfile.js
  src/login/translation/languages/en.json
  src/login/translation/src/login/translation/defaultMessages/userProfile.json
Labels: copy

#413 INPUT: implement custom input for email form(register)
  src/components/Email.js
  src/login/styles/_SignupMain.scss
Labels: investigate, styling

#416 GROUPS: Adds action and reducer files according to new folder structure
  src/components/Settings.js
  src/dashboard-store.js
  src/login/components/App/DashboardApp/Settings/Groups/Groups.js
  src/login/components/App/DashboardApp/Settings/Groups/Groups_container.js
  src/login/components/DataTable/DataTable.js
  src/login/components/DataTable/DataTableRow/DataTableRow.js
  src/login/redux/actions/getAllGroupsData_actions.js
  src/login/redux/reducers/getAllGroupsData_reducer.js
  src/login/sagas/getGroupsAllData.js
  src/login/sagas/rootSaga/groupSagas.js
Labels: clean up, question, refactor, standard
