Repository SUNET/eduid-front, pull requests merged in 2020-06, with the labels that each got.

#316 LOGIN: Updates naming of structural css in line with anatomy outlined in Figma
  src/login/components/App/App.js
  src/login/styles/_anti-bootstrap.scss
  src/login/styles/_base.scss
Labels: standard, styling

#320 LOGIN: Updates naming of structural css in line with anatomy outlined in Figma
  src/login/components/App/App.js
  src/login/components/LoginApp/LoginApp.js
Labels: standard, styling

#321 DASHBOARD MAIN: Updates naming of structural css in line with anatomy outlined in Figma
  src/components/DashboardMain.js
  src/components/Header.js
  src/login/styles/_DashboardMain.scss
  src/login/styles/_Header.scss
Labels: standard, styling

#323 LOGIN: Updates naming of structural css in line with anatomy outlined in Figma
  src/login/styles/_Notifications.scss
  src/login/styles/_base.scss
  src/sagas/common.js
Labels: standard, styling

#324 SIGNUP MAIN: Updates naming of structural css in line with anatomy outlined in Figma
  src/components/AccountCreated.js
  src/components/Captcha.js
  src/components/CodeVerified.js
  src/components/Email.js
  src/components/EmailInUse.js
  src/components/ResendCode.js
  src/components/SignupMain.js
  src/login/styles/_typography.scss
Labels: standard, styling

#325 LOGIN: Updates naming of structural css in line with anatomy outlined in Figma
  src/login/components/LoginApp/LoginForm/LoginForm.js
  src/login/components/LoginApp/ResetPassword/GetEmailLink/GetEmailLink.js
  src/login/components/LoginApp/ResetPassword/ResetPassword.js
  src/login/components/LoginApp/ResetPassword/ResetPasswordText/ResetPasswordText.js
  src/login/components/LoginApp/ResetPassword/SetNewPassword/SetNewPassword.js
  src/login/styles/_ResetPassword.scss
  src/login/styles/_forms.scss
  src/login/styles/_inputs.scss
  src/login/styles/_links.scss
  src/login/styles/_typography.scss
Labels: standard, styling

#333 DEPENDECY: Fixes error message in console
  package-lock.json
  package.json
Labels: bug

#335 ACTIONWRAPPER: Updates naming of structural css in line with anatomy outlined in Figma
  plugins/eduid_action.tou/component.js
  plugins/eduid_action.tou/style.scss
  src/components/ActionWrapper.js
Labels: standard, styling

#337 STYLING: Align the styling for all react parent components
  plugins/eduid_action.tou/component.js
  plugins/eduid_action.tou/style.scss
  src/components/AccountCreated.js
  src/components/ActionWrapper.js
  src/components/Captcha.js
  src/components/CodeVerified.js
  src/components/DashboardMain.js
  src/components/Email.js
  src/components/EmailInUse.js
  src/components/Header.js
  src/components/ResendCode.js
  src/components/SignupMain.js
  src/login/components/App/App.js
  src/login/components/LoginApp/LoginApp.js
  src/login/components/LoginApp/LoginForm/LoginForm.js
  src/login/components/LoginApp/ResetPassword/GetEmailLink/GetEmailLink.js
  src/login/components/LoginApp/ResetPassword/ResetPassword.js
  src/login/components/LoginApp/ResetPassword/ResetPasswordText/ResetPasswordText.js
  src/login/components/LoginApp/ResetPassword/SetNewPassword/SetNewPassword.js
  src/login/styles/_DashboardMain.scss
  src/login/styles/_Header.scss
  src/login/styles/_Notifications.scss
  src/login/styles/_ResetPassword.scss
  src/login/styles/_anti-bootstrap.scss
  src/login/styles/_base.scss
  src/login/styles/_forms.scss
  src/login/styles/_inputs.scss
  src/login/styles/_links.scss
  src/login/styles/_typography.scss
Labels: clean up, standard, styling

#344 TOU: Align styling of the two tous
  plugin-skel/component.js
  plugin-skel/index.js
  plugin-skel/root-saga.js
  plugin-skel/store.js
  plugin-skel/test.js
  plugins/eduid_action.mfa/component.js
  plugins/eduid_action.mfa/index.js
  plugins/eduid_action.mfa/root-saga.js
  plugins/eduid_action.mfa/store.js
  plugins/eduid_action.mfa/test.js
  plugins/eduid_action.tou/ToU-test.js
  plugins/eduid_action.tou/component.js
  plugins/eduid_action.tou/index.js
  plugins/eduid_action.tou/root-saga.js
  plugins/eduid_action.tou/store.js
  plugins/eduid_action.tou/style.scss
  src/actions/ActionMain.js
  src/components/ActionMain.js
  src/containers/ActionMain.js
  src/containers/ActionWrapper.js
  src/plugins-saga.js
  src/reducers/ActionMain.js
  src/sagas/ActionMain.js
  src/tests/ActionMain-test.js
Labels: clean up, refactor, standard, styling

#350 ERROR MESSAGE: Adjust positioning of error text for various devices
  src/login/styles/_Notifications.scss
Labels: bug, styling
