Repository SUNET/eduid-front, pull requests merged in 2020-11, with the labels that each got.

#466 GROUP MANAGEMENT: Attempt at isolating API call to '/all-data' endpoint
  src/components/Settings.js
  src/login/components/App/DashboardApp/Settings/Groups/Groups.js
  src/login/components/App/DashboardApp/Settings/Groups/GroupsContainer.js
  src/login/redux/actions/getAllDataGroupActions.js
  src/login/redux/reducers/getAllGroupsDataReducer.js
  src/login/redux/sagas/groups/allDataSaga.js
  src/login/redux/sagas/rootSaga/groupsSagas.js
Labels: logic, refactor

#461 SECURITY KEY: updated styling for security key table
  src/components/Security.js
  src/login/styles/_buttons.scss
  src/login/styles/_tables.scss
Labels: layout, styling

#462 VETTING: Add info about vetting by letter to keep user informed after requesting a letter
  i18n/src/login/translation/defaultMessages/userProfile.json
  src/components/LetterProofing.js
  src/components/LookupMobileProofing.js
  src/containers/LetterProofing.js
  src/dashboard-root-saga.js
  src/login/styles/_Nins.scss
  src/login/translation/defaultMessages/userProfile.js
  src/login/translation/languages/en.json
  src/login/translation/languages/sv.json
  src/login/translation/src/i18n-messages.json
  src/login/translation/src/login/translation/defaultMessages/userProfile.json
  src/notify-middleware.js
  src/sagas/LetterProofing.js
Labels: investigate

#469 GROUP MANAGEMENT: Adds Groups stylesheet for styling
  src/login/components/App/DashboardApp/Settings/Groups/Groups.js
  src/login/components/App/DashboardApp/Settings/Groups/GroupsContainer.js
  src/login/components/DataPanel/DataPanel.js
  src/login/components/DataPanel/EditDataBox.js
  src/login/components/DataPanel/ViewDataTable.js
  src/login/components/Wizard/WizardPanel.js
  src/login/styles/_Groups.scss
  src/login/styles/index.scss
Labels: clean up, styling

#477 GROUP MANAGEMENT: Adds render logic to respond to user data
  src/login/components/App/DashboardApp/Settings/Groups/Groups.js
  src/login/components/App/DashboardApp/Settings/Groups/GroupsContainer.js
  src/login/components/DataPanel/DataPanel.js
  src/login/components/DataPanel/EditMode.js
  src/login/components/DataPanel/ViewDataTable.js
  src/login/components/DataPanel/ViewMode.js
  src/login/components/Wizard/WizardPanel.js
  src/login/redux/reducers/getAllGroupsDataReducer.js
  src/login/redux/sagas/groups/allDataSaga.js
  src/login/styles/_Groups.scss
Labels: layout, logic, styling

#479 GROUP MANAGEMENT: Renders group list and further info on click
  src/login/components/App/DashboardApp/Settings/Groups/GroupListItem.js
  src/login/components/DataPanel/DataPanel.js
  src/login/components/DataPanel/EditMode.js
  src/login/components/DataPanel/GroupList.js
  src/login/components/DataPanel/ViewMode.js
  src/login/styles/_Groups.scss
Labels: layout, logic

#481 GROUP MANAGEMENT: Rendering groups in single list
  src/login/components/App/DashboardApp/Settings/Groups/GroupListItem.js
  src/login/components/App/DashboardApp/Settings/Groups/GroupsContainer.js
  src/login/components/DataPanel/EditMode.js
  src/login/components/DataPanel/GroupList.js
  src/login/styles/_Groups.scss
Labels: logic, styling

#482 GROUP MANAGEMENT: Quick file cleanup
  src/components/Settings.js
  src/login/components/DataPanel/DataPanelContainer.js
  src/login/components/GroupManagement/EditMode/EditMode.js
  src/login/components/GroupManagement/GroupDataPanel.js
  src/login/components/GroupManagement/GroupList.js
  src/login/components/GroupManagement/GroupListItem.js
  src/login/components/GroupManagement/GroupManagement.js
  src/login/components/GroupManagement/GroupManagementContainer.js
  src/login/components/GroupManagement/Wizard/WizardPanel.js
Labels: clean up

#487 GROUP MANAGEMENT: Group data in editMode persists reload
  src/login/components/GroupManagement/EditMode/EditMode.js
  src/login/components/GroupManagement/GroupDataPanel.js
  src/login/translation/languages/en.json
  src/login/translation/languages/sv.json
Labels: refactor

#488 GROUP MANAGEMENT: Replaces username for user_identifier in user/group relationship hack
  src/login/components/GroupManagement/GroupList.js
  src/login/components/GroupManagement/GroupManagementContainer.js
Labels: clean up
