Repository SUNET/eduid-front, pull requests merged in 2020-07, with the labels that each got.

#363 VETTING: Refactor of <VerifyIdentity> to be able to better follow how vetting buttons render
  src/vetting-registry.js
Labels: refactor

#362 TABLES: Refactor tables that hold user data to make them more generic
  src/components/Emails.js
  src/components/Mobile.js
  src/login/components/Buttons/ButtonRemoveData.js
  src/login/components/Buttons/ButtonTableData.js
  src/login/components/DataTable/DataTable.js
  src/login/components/DataTable/DataTableRow/DataStatus/DataStatus.js
  src/login/components/DataTable/DataTableRow/DataTableRow.js
  src/login/styles/_buttons.scss
  src/login/styles/_tables.scss
Labels: refactor

#365 VETTING: Refactor of <VerifyIdentity> to be able to better follow how vetting buttons render
  src/components/VerifyIdentity.js
Labels: refactor

#368 GROUPS: refactor of cookie functionality from component to plain .js function
  src/login/app_utils/checkForCookie.js
  src/login/components/App/DashboardApp/Settings/Groups.js
Labels: refactor

#375 VETTING: Disables/enabled post and phone vetting buttons based on valid nin
  src/components/LetterProofing.js
  src/components/VerifyIdentity.js
  src/containers/LetterProofing.js
  src/tests/VerifyIdentity-test.js
  src/vetting-registry.js
Labels: bug

#377 SWEDISH TRANSLATION: Adjust Swedish text in vetting buttons and help text
  i18n/src/login/translation/defaultMessages/userProfile.json
  src/login/translation/defaultMessages/userProfile.js
  src/login/translation/languages/en.json
  src/login/translation/languages/sv.json
  src/login/translation/src/i18n-messages.json
  src/login/translation/src/login/translation/defaultMessages/userProfile.json
Labels: copy

#381 GROUP MGMT: Introduction of new folder structure for sagas
  src/dashboard-root-saga.js
  src/login/components/App/DashboardApp/Settings/Groups/Group_sagas.js
  src/login/sagas/getData.js
  src/login/sagas/getGroups.js
  src/login/sagas/getGroupsAllData.js
  src/login/sagas/rootSaga/groupSagas.js
Labels: :bulb:, refactor, standard
