Repository SUNET/eduid-front, pull requests merged in 2020-09, with the labels that each got.

#419 GROUP MGMT: Draft logic for <Groups/> parent
  src/components/Settings.js
  src/login/components/App/DashboardApp/Settings/Groups/Groups.js
  src/login/styles/_base.scss
Labels: logic, refactor, standard

#420 GROUP MANAGEMENT: Applies logic to render wizard vs Create Group button
  babel.config.js
  package-lock.json
  package.json
  src/login/components/App/DashboardApp/Settings/Groups/Groups.js
  src/login/components/DataTable/DataTable.js
  src/login/components/DataTable/DataTableRow/DataTableRow.js
  src/login/components/Wizard/WizardPanel.js
Labels: logic, standard

#417 INPUT: Validation for confirm modal form
  i18n/src/login/translation/defaultMessages/generalApp.json
  i18n/src/login/translation/messageIndex.json
  src/components/ConfirmModal.js
  src/components/ConfirmModalForm.js
  src/components/Emails.js
  src/components/Security.js
  src/login/components/Inputs/CustomInput.js
  src/login/styles/_inputs.scss
  src/login/styles/_modals.scss
  src/login/translation/defaultMessages/generalApp.js
  src/login/translation/languages/en.json
  src/login/translation/languages/sv.json
  src/login/translation/messageIndex.js
  src/login/translation/src/i18n-messages.json
  src/login/translation/src/login/translation/defaultMessages/generalApp.json
  src/login/translation/src/login/translation/messageIndex.json
Labels: copy

#421 GROUP MANAGEMENT: Adds logic for view-mode and edit-mode for groups data
  src/login/components/App/DashboardApp/Settings/Groups/Groups.js
  src/login/components/DataPanel/DataPanel.js
  src/login/components/DataPanel/EditDataBox.js
  src/login/components/DataPanel/ViewDataTable.js
  src/login/components/Wizard/WizardPanel.js
Labels: logic, standard

#424 Separate validation for email(register)/emails(adding emails)
  src/components/Email.js
  src/components/Emails.js
  src/login/app_utils/validation/validateEmail.js
Labels: clean up

#426 VETTING BY PHONE: Fixing logic to handle modals to prompt user to add/verify a phone number
  src/actions/LookupMobileProofing.js
  src/components/LookupMobileProofing.js
  src/containers/LookupMobileProofing.js
  src/sagas/LookupMobileProofing.js
  src/tests/LookupMobileProofing-test.js
  src/vetting-registry.js
Labels: :rotating_light:, bug, logic

#425 MODAL: Import generic confirm modal for email(register)
  src/components/Email.js
  src/components/GenericConfirmModal.js
  src/login/styles/_modals.scss
Labels: clean up

#423 INPUT: handle button in confirm modal
  src/components/ConfirmModal.js
  src/components/Emails.js
  src/components/LetterProofing.js
  src/components/Mobile.js
  src/components/Security.js
  src/containers/ConfirmModal.js
  src/login/styles/_buttons.scss
Labels: bug, styling

#430 GROUP MANAGEMENT: Adds API call and render of response data in DataPanel
  src/dashboard-store.js
  src/login/components/App/DashboardApp/Settings/Groups/Groups.js
  src/login/components/DataPanel/DataPanel.js
  src/login/components/DataPanel/DataPanelContainer.js
  src/login/components/DataPanel/EditDataBox.js
  src/login/components/DataPanel/ViewDataTable.js
  src/login/redux/actions/getAllGroupsDataActions.js
  src/login/redux/reducers/getAllGroupsDataReducer.js
  src/login/sagas/getGroupsAllData.js
Labels: refactor

#431 Dupplicated GenericConfrimModal and renamed to NotificationModal
  src/components/ChangePasswordDisplay.js
  src/components/Email.js
  src/components/LetterProofing.js
  src/components/LookupMobileProofing.js
  src/components/Security.js
  src/login/components/Modals/NotificationModal.js
  src/tests/ChangePasswordDisplay-test.js
Labels: investigate

#436 GROUP MANAGEMENT: move sagas to redux/ folder
  src/components/Settings.js
  src/dashboard-root-saga.js
  src/login/components/App/DashboardApp/Settings/Groups/Groups.js
  src/login/components/App/DashboardApp/Settings/Groups/GroupsContainer.js
  src/login/components/DataPanel/EditDataBox.js
  src/login/components/DataPanel/ViewDataTable.js
  src/login/redux/actions/createGroupActions.js
  src/login/redux/sagas/getDataRequest.js
  src/login/redux/sagas/groups/allDataSaga.js
  src/login/redux/sagas/groups/createGroupSaga.js
  src/login/redux/sagas/groups/groupsSaga.js
  src/login/redux/sagas/postDataRequest.js
  src/login/redux/sagas/rootSaga/groupsSagas.js
  src/login/sagas/rootSaga/groupSagas.js
Labels: clean up, refactor, standard

#433 MODAL: Import notification modal in Eidas
  src/components/Eidas.js
  src/login/components/Modals/NotificationModal.js
Labels: investigate, refactor

#435 MODAL: Import NotificationModal for delete account
  src/components/DeleteAccount.js
  src/tests/DeleteAccount-test.js
Labels: investigate

#446 SECURITY KEY: Fix undefined value for description
  src/containers/Security.js
Labels: bug

#443 MODAL: Change first modal button text for vetting by phone
  src/components/LookupMobileProofing.js
Labels: copy

#444 MODAL: Corrected spelling error for modal title by vetting phone
  i18n/src/login/translation/defaultMessages/userProfile.json
  src/components/LookupMobileProofing.js
  src/login/translation/defaultMessages/userProfile.js
  src/login/translation/languages/en.json
  src/login/translation/src/i18n-messages.json
  src/login/translation/src/login/translation/defaultMessages/userProfile.json
Labels: copy
