Repository SUNET/eduid-front, pull requests merged in 2021-04, with the labels that each got.

#545 GROUP MANAGEMENT: Renders checkboxes for editing invite roles
  src/login/app_utils/helperFunctions/checkboxHelpers.js
  src/login/components/GroupManagement/InviteRoleCheckboxes.js
  src/login/components/GroupManagement/Invites/EditRolesForm.js
  src/login/components/GroupManagement/Invites/InviteListItem.js
  src/login/components/GroupManagement/Invites/InvitesList.js
  src/login/styles/_Groups.scss
  src/tests/helperFunctions/checkboxHelpers-test.js
Labels: logic

#544 NIN: add show/hide function for the verified users
  src/components/NinDisplay.js
  src/tests/NinDisplay-test.js
Labels: logic

#551 SETTINGS/IDENTITY: Minor spelling
  src/login/translation/languages/sv.json
Labels: copy

#557 CHANGEPASSWORD : Cancel button text color to be changed
  src/components/Captcha.js
  src/components/ChangePasswordForm.js
  src/components/DeleteModal.js
  src/components/GenericConfirmModal.js
  src/login/components/Modals/ConfirmModal.js
  src/login/components/Modals/NotificationModal.js
  src/login/styles/_buttons.scss
Labels: prod, staging, styling

#563 NOTIFICATIONDOT: Fix wrong spelling and removal av duplicate words
  src/login/translation/languages/sv.json
Labels: copy

#565 IDENTITY: Fix Incorrect nin data and specific fault massage added
  i18n/src/login/translation/defaultMessages/errors.json
  src/components/NinDisplay.js
  src/login/translation/defaultMessages/errors.js
  src/login/translation/src/login/translation/defaultMessages/errors.json
  src/notify-middleware.js
Labels: bug
