Repository SUNET/eduid-front, pull requests merged in 2021-01, with the labels that each got.

#504 GROUP MANAGEMENT: Adds create invite functionality
  src/dashboard-root-saga.js
  src/dashboard-store.js
  src/login/components/GroupManagement/EditMode/EditMode.js
  src/login/components/GroupManagement/EmailForm.js
  src/login/components/GroupManagement/GroupDataPanel.js
  src/login/components/GroupManagement/GroupManagement.js
  src/login/components/GroupManagement/GroupManagementContainer.js
  src/login/components/GroupManagement/Groups/EditGroup.js
  src/login/components/GroupManagement/Groups/GroupListItem.js
  src/login/components/GroupManagement/Groups/GroupsList.js
  src/login/components/GroupManagement/Groups/GroupsParent.js
  src/login/components/GroupManagement/Invites/CreateInvite.js
  src/login/components/GroupManagement/Invites/CreateInviteContainer.js
  src/login/components/GroupManagement/Invites/InviteListItem.js
  src/login/components/GroupManagement/Invites/InvitesList.js
  src/login/components/GroupManagement/Invites/InvitesListContainer.js
  src/login/components/GroupManagement/Invites/InvitesParent.js
  src/login/components/GroupManagement/Invites/InvitesParentContainer.js
  src/login/components/GroupManagement/Wizard/WizardParent.js
  src/login/redux/actions/createInviteActions.js
  src/login/redux/actions/getAllGroupMgmtDataActions.js
  src/login/redux/actions/getOutgoingInvitesActions.js
  src/login/redux/reducers/groupsReducer.js
  src/login/redux/reducers/invitesReducer.js
  src/login/redux/sagas/groups/getAllDataSaga.js
  src/login/redux/sagas/groups/getAllGroupsSaga.js
  src/login/redux/sagas/invites/createInviteSaga.js
  src/login/redux/sagas/invites/getAllOutgoingInvitesSaga.js
  src/login/redux/sagas/rootSaga/groupManagementSagas.js
  src/login/styles/_Groups.scss
Labels: help, layout, logic, refactor, standard, styling

#507 ESLINT: Turn on eslint rules: no-undef by removing "off" in rules
  .eslintrc.js
  src/components/Security.js
  src/login/components/LoginApp/LoginForm/LoginForm_actions.js
  src/sagas/cbor.js
Labels: clean up, epic

#513 FOOTER: changed copyright year 2021
  i18n/src/login/translation/defaultMessages/generalApp.json
  src/login/translation/defaultMessages/generalApp.js
  src/login/translation/languages/en.json
  src/login/translation/languages/sv.json
  src/login/translation/src/i18n-messages.json
  src/login/translation/src/login/translation/defaultMessages/generalApp.json
Labels: copy

#505 VETTING: by phone, when disabled the information text "settings" is linked to settings page
  i18n/src/login/translation/defaultMessages/userProfile.json
  package-lock.json
  package.json
  src/components/LookupMobileProofing.js
  src/components/Mobile.js
  src/containers/LookupMobileProofing.js
  src/login/styles/_Nins.scss
  src/login/translation/defaultMessages/userProfile.js
  src/login/translation/languages/en.json
  src/login/translation/languages/sv.json
  src/login/translation/src/i18n-messages.json
  src/login/translation/src/login/translation/defaultMessages/userProfile.json
Labels: investigate, layout, styling

#515 VETTING: Align code structure and add additional tests for LookupMobileProofing-test
  src/tests/LookupMobileProofing-test.js
Labels: testing

#518 GROUPMANAGEMENT: FIx spelling error
  src/login/components/GroupManagement/GroupManagement.js
Labels: copy

#519 ESLINT: Turn on eslint rules: no case declarations by removing "off" in rules
  .eslintrc.js
  src/reducers/DashboardConfig.js
  src/reducers/Emails.js
  src/reducers/LetterProofing.js
  src/reducers/Mobile.js
  src/reducers/Nins.js
Labels: clean up

#521 SETTINGS: Validation for personal data
  i18n/src/login/translation/defaultMessages/errors.json
  src/components/PersonalData.js
  src/login/components/Inputs/CustomInput.js
  src/login/styles/_inputs.scss
  src/login/translation/defaultMessages/errors.js
  src/login/translation/languages/en.json
  src/login/translation/languages/sv.json
  src/login/translation/src/login/translation/defaultMessages/errors.json
  src/sagas/PersonalData.js
  src/tests/PersonalData-test.js
Labels: bug
