Repository SUNET/eduid-front, pull requests merged in 2021-02, with the labels that each got.

#527 REGISTER: Cancel button text color and accept "TOU" hover effect to be changed
  src/login/styles/_buttons.scss
Labels: styling

#531 GROUP MANAGEMENT: Adds navigation functionality to EditGroup nav
  src/login/components/GroupManagement/Groups/DeleteGroup.js
  src/login/components/GroupManagement/Groups/EditGroup.js
  src/login/components/GroupManagement/Invites/CreateInvite.js
  src/login/components/GroupManagement/Invites/EditInvite.js
  src/login/components/GroupManagement/Invites/InvitesList.js
  src/login/styles/_Groups.scss
  src/login/styles/variables.scss
  src/variables.scss
Labels: logic

#536 GROUP MANAGEMENT: Lists invites by unique email address and corresponding roles
  package.json
  src/login/app_utils/helperFunctions/invitesByRole.js
  src/login/components/GroupManagement/Invites/InviteListItem.js
  src/login/components/GroupManagement/Invites/InvitesList.js
  src/login/components/GroupManagement/Invites/InvitesListContainer.js
  src/login/components/GroupManagement/Invites/InvitesParent.js
  src/login/components/GroupManagement/Invites/InvitesParentContainer.js
  src/tests/helperFunctions/invitesByRole-test.js
Labels: logic, refactor, testing

#535 SIGNUP: Add promise / yield until a response from backed is received.
  src/actions/Captcha.js
  src/components/Captcha.js
  src/containers/Captcha.js
  src/reducers/Captcha.js
  src/sagas/Captcha.js
  src/tests/Captcha-test.js
Labels: bug
