Repository SUNET/eduid-front, pull requests merged in 2021-05, with the labels that each got.

#571 NOTIFICATION: Fix console log error and show correct error message after letter proofing failed
  src/notify-middleware.js
Labels: bug, staging

#587 GROUP MANAGEMENT: Add conditional for group management API calls on load
  src/components/DashboardMain.js
  src/components/Settings.js
  src/containers/DashboardMain.js
  src/dashboard-root-saga.js
  src/login/redux/actions/addDataToStoreActions.js
  src/login/redux/reducers/groupsReducer.js
Labels: bug, staging

#588 LOGIN: Update LoginForm file structure to the current standard
  src/login/app_config/login-rootReducer.js
  src/login/components/GroupManagement/EmailForm.js
  src/login/components/GroupManagement/GroupNameForm.js
  src/login/components/GroupManagement/Groups/CreateGroup.js
  src/login/components/LoginApp/LoginForm/LoginForm.js
  src/login/components/LoginApp/LoginForm/LoginForm_actions.js
  src/login/components/LoginApp/LoginForm/LoginForm_container.js
  src/login/components/LoginApp/LoginForm/LoginForm_reducer.js
  src/login/components/LoginApp/LoginForm/LoginForm_sagas.js
  src/login/redux/actions/addDataToStoreActions.js
  src/login/redux/reducers/loginReducer.js
Labels: refactor

#591 RESETPASSWORD: Clean up of reset password unused old files
  src/login/app_config/login-rootReducer.js
  src/login/app_config/login-rootSaga.js
  src/login/components/App/App.js
  src/login/components/LoginApp/LoginApp.js
  src/login/components/LoginApp/LoginForm/LoginForm.js
  src/login/components/LoginApp/ResetPassword/EmailLinkSent/EmailLinkSent.js
  src/login/components/LoginApp/ResetPassword/EmailLinkSent/EmailLinkSent_container.js
  src/login/components/LoginApp/ResetPassword/GetConfirmationCode/GetConfirmationCode.js
  src/login/components/LoginApp/ResetPassword/GetConfirmationCode/GetConfirmationCode_container.js
  src/login/components/LoginApp/ResetPassword/GetEmailLink/GetEmailLink.js
  src/login/components/LoginApp/ResetPassword/GetEmailLink/GetEmailLink_actions.js
  src/login/components/LoginApp/ResetPassword/GetEmailLink/GetEmailLink_container.js
  src/login/components/LoginApp/ResetPassword/GetEmailLink/GetEmailLink_reducer.js
  src/login/components/LoginApp/ResetPassword/GetEmailLink/GetEmailLink_sagas.js
  src/login/components/LoginApp/ResetPassword/ResetPassword.js
  src/login/components/LoginApp/ResetPassword/ResetPasswordText/ResetPasswordText.js
  src/login/components/LoginApp/ResetPassword/ResetPassword_container.js
  src/login/components/LoginApp/ResetPassword/SetNewPassword/SetNewPassword.js
  src/login/components/LoginApp/ResetPassword/SetNewPassword/SetNewPassword_container.js
  src/login/components/LoginApp/ResetPassword/UseConformationCode/UseConfirmationCode.js
  src/login/components/LoginApp/ResetPassword/UseConformationCode/UseConfirmationCode_container.js
Labels: clean up

#592 Clean up/Update init files
  src/login/app_config/login-rootSaga.js
  src/login/app_init/init_actions.js
  src/login/app_init/init_container.js
  src/login/app_init/init_reducer.js
  src/login/app_init/init_sagas.js
  src/login/redux/actions/postResetPasswordActions.js
Labels: clean up
